name: otaku
title: otaku
org: Derrick Ampy
author: Derrick Ampy
author_url: https://github.com/dsampy
base_url: ''
ctx_path: ''
interpolate: false 
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: otaku
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
profiles:
  development:
    deploy: nil 
  production:
    base_url: http://dsampy.github.io/otaku-site
    ctx_path: /otaku-site
    asciidoctor:
      :attributes:
        base_url: http://dsampy.github.io/otaku-site
        ctx_path: /otaku-site
        imagesdir: http://dsampy.github.io/otaku-site/images 
    deploy:
      host: github_pages
      branch: gh-pages
